pipeline {
    agent any  // Indique que le pipeline peut s'exécuter sur n'importe quel agent disponible

    stages {
        stage('Build') {  // Définition de la première étape du pipeline
            steps {
                script {
                    echo 'Building application for Production...'  // Message affiché dans les logs
                    // Ajoutez ici les commandes nécessaires pour construire l'application
                }
            }
        }
        stage('Test') {  // Définition de la deuxième étape du pipeline
            steps {
                script {
                    echo 'Running tests for Production...'  // Message affiché dans les logs
                    // Ajoutez ici les commandes nécessaires pour exécuter les tests
                }
            }
        }
        stage('Deploy') {  // Définition de la troisième étape du pipeline
            steps {
                script {
                    echo 'Deploying to Production...'  // Message affiché dans les logs
                    // Ajoutez ici les commandes nécessaires pour déployer l'application
                }
            }
        }
    }
}
